### ISSUE TITLE
Add hybrid synchronisation and local boxes handling

### ISSUE THREAD

**Issue by capt-nemo429** [nautls/nautilus-wallet#45]
Combines light and full synchronization to keep track of all owned boxes and transactions locally while maintain fast sync times. This feature will also serve as basis to 'Transactions history' tab (#44).

## Todo
- [x] Add UTxO data model
- [x] Add transactions data model
- [x] ~Migrate to backend API v1~
- [x] #37 
- [x] ~Add EIP-29 parser~
- [ ] Add full sync mechanism
- [ ] #44 
- [ ] Add full and light box/balance fetching mechanism based on the status of the full sync process.
